# Generated by Django 2.0.2 on 2018-02-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('category', models.CharField(max_length=25, verbose_name=('Grocery', 'petrol', 'food', 'entertainment'))),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
    ]
