# Generated by Django 2.0.2 on 2018-02-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanager', '0003_auto_20180224_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='CATEGORY',
            field=models.CharField(choices=[('FOOD', 'FOOD'), ('GROCERY', 'GROCERY'), ('PETROL', 'PETROL'), ('ENTERTAINMENT', 'ENTERTAINMENT')], max_length=25),
        ),
    ]
