# Generated by Django 2.0.2 on 2018-02-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanager', '0004_auto_20180224_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
