# Generated by Django 2.0.2 on 2018-02-24 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensemanager', '0005_auto_20180225_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='sr_no',
            new_name='id',
        ),
    ]
